### PR TITLE
Added support for multiple maildirs

### PR DESCRIPTION
**Pull request by phikal**
**Note:** I just started using StumpWM just over a week ago, so I might have messed up a few things. And haven't had that much experience with Common Lisp per se... but at least it works on my machine.

---

As the title says, changed the maildir module to support multiple maildirs -- at the cost of having to change the old interface. Mail changes are:
- changing the format string from `%M` to `%D` (Mail- **d** -ir, I know it's bad)
- substituting `*maildir-path*` for `*maildir-alist*`
- dropping a few older functions

I could imagine the possibility of adding backwards compatibility support, but there problem would be a very hack-y (in the bad sense) result that would a harder to hack around with (in the good sense).

I'm looking forward to criticism and improvments, but it will probably take a while (~1-2 weeks) to fix if these are really deep.

### CODE REVIEW

**Comment by dbjergaard** [comment]
Hi,

My only objection to this the change from %M to %D, can you explain the motivation to me?

**Comment by phikal** [comment]
As the old Notes section said,

> The %M mode line formatter is also used by the 'mem' module.

so I thought it was better to avoid the confusion. If that's an issue, I can change it back, but other than backwards compatibility (on an issue that's rather simple to fix) I don't know why this name-conflict shouldn't be resolved.

**Comment by dbjergaard** [comment]
Hi, I just merged another PR that conflicts with this PR. Can you resolve the conflicts? I'm ok with the M to D change given your justification.

**Comment by phikal** [comment]
Will do, but as far as I see, I deleted that part of the file, so there shoudln't be that much to merge.

**Comment by phikal** [comment]
Hope it worked.

**Comment by phikal** [comment]
I just realized that the main README still mentions %M as the format string. That should probably be fixed.

**Pull request merged**
