### PR TITLE
Adds winner-mode module.

### PR DESCRIPTION
**Pull request by ralt**
winner-mode lets you have a similar workflow as in emacs, using its
winner-mode. Whenever possible, the layout is dumped to a file, and a
few commands let you cycle through the dumped layouts.

This module would love https://github.com/stumpwm/stumpwm/pull/230 to be merged, and the README.org could be updated to have the new hooks in it.

### CODE REVIEW

**Comment by jorams** [comment]
This looks good to me, though I haven't tested it.

**Comment by ralt** [comment]
I'd like this PR to wait for https://github.com/stumpwm/stumpwm/pull/230 to be merged, since `winner-mode:add-hooks` might be useless if it turns out merged in, so I'd remove it.

**Comment by ralt** [comment]
I've fixed the README and removed the useless macro, this PR is now mergeable (after review). I'll amend the README when new hooks are available later on.

**Comment by dbjergaard** [comment]
I'm only seeing the initial commit, I have to admit I'm not sure how to emend PRs with new commits, just that I've seen it done before elsewhere.

**Comment by ralt** [comment]
Sorry, I rebased to have a single commit in this PR. I meant that I'll do another PR later on when the new hooks will be available, so that winner-mode's README will have a more extensive documentation.

**Comment by dbjergaard** [comment]
Let me know when this one is ready :)

**Comment by ralt** [comment]
@dbjergaard there we go :-)

**Pull request merged**
