### PR TITLE
update-readme.sh: Link to markdown file if one is present

### PR DESCRIPTION
**Pull request by PuercoPop**
Update the `update-readme.sh` script so that the link in the top-level readme points to `README.md` ifone is present. Otherwise defaults to `README.org`

### CODE REVIEW

**Comment by lxbarbosa** [comment]
some minor observations:

Bash can infer string variables, so double quote are not necessary: `var=README.md`.
Bash `[[ $var]]`  double bracket is meant so users do not need to double-quote variables inside of it.

I thought it may be helpful. :)

**Comment by PuercoPop** [comment]
@lxbarbosa Thanks for chipping in!

> What about globbing README extensions: README_PATH=README.{md,org}

Although I get the general idea of what you are proposing and I think it will lead to simpler code I'm not quite sure of the specific suggestion. Can you leave a review with a `suggestion` comment making the proposal concrete?

> Bash 4.4/5.0 added some neat features that may turn awk dep optional

I'm on Ubuntu 18.04 and have Bash 4.4 so I guess it is ok to, although we do have *BSD users that don't run bash. If you make a _separate_ PR replacing awk usage with bash built-in features we can evaluate if the code is more clear to the point that the loss of portability is worth it.

**Comment by aartaka** [comment]
How about adding a line like "it's preferrable for your README to be an Org Mode file." to the main README contributing instuctions ("Submitting the module" header and project directory listings in "A pseudo-tutorial" header)? 

The reason one can accidentally use Markdown can be that it's not explicitly recommended to use Org. It was the case for me, for example. I've just used what `quickproject:make-project` generated for me, and it was `.md` file :)

There are mentions of Org READMEs aroung manual, but these are not emphasized enough to be easily noticeable.

**Comment by dmb2** [comment]
Lets allow: README, README.md, README.org and README.txt via:
```
README_PATH=README{,.txt,.md,.org}
```
And strongly encourage .org, but still allow other module writer's preferences.

**Comment by PuercoPop** [comment]
@dmb2 I agree, but as I told @elxbarbosa my shell-fu is weak. I'm not sure how to apply your suggestion. I understand that the `README{,.txt,.md,.org}` glob would expand correctly but I don't know how to expand it in the context of the module directory, `(dirname $f)`.

**Pull request merged**
