### PR TITLE
add option :leave-alone for *caps-lock-behavior* to not send any CapsLock option at all

### PR DESCRIPTION
**Pull request by m-g-r**
reason:
I configure caps lock with xmodmap in a personal fashion.
This PR allows to set the kbd-layouts:*caps-lock-behavior* to :leave-alone
which will mak kbd-layouts to not change the caps lock configuration at all
with setxkbmap, which just caused trouble in my case.

general remark:
I also do not see any reason why kbd-layout should try to mess with the setting by default.

### CODE REVIEW

**Comment by jorams** [comment]
Does this change actually work? It looks like `switch-keyboard-layout` gets called with the defaults while loading the module, so the behaviour of `:normal` gets applied anyway.

> I also do not see any reason why kbd-layout should try to mess with the setting by default.

I agree with this. Same for setting the keyboard layout to `us`.

**Comment by dmb2** [comment]
Why do we need leave-alone when a user can just not use the module?

**Comment by m-g-r** [comment]
@joarms oddly enough it worked for me. it would initially set caps-lock to caps-lock, and that is the default of my x-server nevertheless, so it doesn't disturb the following setup by xmodmap. But after the initial setup, :leave-alone would work and prevent further meddling with the caps lock key.

I'll look again to prevent the initial setup as well. But this will make the PR a bit bigger. I'll push, have a look.

dmb2: oh, but I do want to use the module as I want to switch between US and DE (German) layout. But that doesn't mean I want it to change the caps lock setting.

**Comment by m-g-r** [comment]
@joarms Do you prefer it like this?

**Comment by jorams** [comment]
@m-g-r Ah, I understand. Your xmodmap changes depend on caps lock being caps lock, and because that's the default they would still work.

This is definitely better. Now loading the module doesn't suddenly change one's keyboard layout. It's not completely backwards compatible, but I don't think that matters much here. I'd expect any users of this module to actually configure it.

@dmb2 What do you think?

**Comment by dmb2** [comment]
I'm sorry I didn't fully grok the use case.  Merged as is.

**Comment by m-g-r** [comment]
Thanks guys.

**Pull request merged**
