### PR TITLE
A simple module to show the hostname in the mode-line

### PR DESCRIPTION
**Pull request by Jehops**
This is my first module and my first pull request, so please let me know if I've done anything stupid.

### CODE REVIEW

**Comment by jorams** [comment]
Looks pretty good to me, though maybe it could use a little note that, while this works in SBCL, CCL, ECL and, because of the `SPLIT-STRING` use, CLISP (as far as I know, possibly more), `MACHINE-INSTANCE` isn't specified to return a hostname.

(P.S. As a point of consideration, I would personally just put the package definition in `hostname.lisp`. That's a matter of taste, though.)

**Comment by Jehops** [comment]
Using `MACHINE-INSTANCE` sounds like a problem.  I'm on FreeBSD, so other than SBCL, I don't know of any other implementation (that I know of) I can use to test.  Can you suggest a more reliable alternative for getting the hostname?

Instead of split-string, would
````lisp
(defpackage #:hostname
  (:use #:cl :cl-ppcre :stumpwm))

(defun fmt-hostname (ml)
  "Return hostname"
  (declare (ignore ml))
  (format nil "~a" (car (split "\\." (machine-instance)))))
````
be more portable?

For your last point,  you're suggesting I take the contents of `package.lisp` and put them at the top of `hostname.lisp`?

**Comment by jorams** [comment]
I don't think using `MACHINE-INSTANCE` is really a problem, but noting the fact that it isn't guaranteed to return the hostname in every Common Lisp seems like a good idea. A truly portable way to get the machine's hostname doesn't exist, as far as I know.

Since `split-string` is supplied by StumpWM that would be ok to use, no need for CL-PPCRE. I now see I actually misread the `split-string` call, I thought you were splitting on ' ' (a space) instead of '.'.

For reference, this is what a bunch of CL implementations return for `(machine-instance)`:

Implementation | (machine-instance)
--------------------|-------------------------
SBCL | "\<hostname\>"
CCL | "\<hostname\>"
CLISP | "\<hostname\> [\<ip\>]"
ECL | "\<hostname\>"
CMUCL | "\<hostname\>"
ABCL | "\<hostname\>"

The split on '.' would be problematic on CLISP if the hostname doesn't contain a '.', so I think it's a good idea to change `(split-string (machine-instance) ".")` to `(split-string (machine-instance) ". ")`. (Also splitting on space). Otherwise I don't think there's a problem; StumpWM itself is less portable than this module.

My last point was indeed to put the contents of `package.lisp` at the top of `hostname.lisp`. This because there's only one file using the package and the package definition is very simple.

**Comment by Jehops** [comment]
I've updated with your suggestions.  I moved the contents of `package.lisp` to `hostname.lisp` and everything was fine, but if I remove `package.lisp` I get an error.

**Comment by dbjergaard** [comment]
Hi 

You must have an asd file for stumpwm to find it. As far as putting the package def in the implementation:  it should work, check other modules to see if you missed something obvious. 

    Dave

**Comment by Jehops** [comment]
Ah, of course.  Thanks.  I was referring to `package.lisp`.  Fixed and removed `package.lisp`.

**Comment by jorams** [comment]
Looks good to me! :+1:

**Comment by Jehops** [comment]
Awesome.

**Pull request merged**
