### PR TITLE
Pinentry readme screenshot

### PR DESCRIPTION
**Pull request by equwal**
Add a screenshot to the readme to demonstrate the usage of the `pinentry` module.

pinentry

### CODE REVIEW

**Comment by dmb2** [comment]
I do not want the repos filled with binary files.  The logos are the exception that proves the rule.

**Comment by equwal** [comment]
> I do not want the repos filled with binary files. The logos are the exception that proves the rule.

@dmb2 
So are screenshots off the table, or can they just be hosted elsewhere?

**Comment by dmb2** [comment]
Given how links bitrot, screenshots should be avoided unless necessary.  I don't see how they're necessary in this context.

**Comment by equwal** [comment]
> Given how links bitrot, screenshots should be avoided unless necessary. I don't see how they're necessary in this context.

I think in the context of a contrib with a user interface they are very germane. They could be cropped and compressed to be under a certain size if desired, there isn't much to a plaintext message box.

**Pull request closed without merging**
